### ISSUE TITLE
adding frontend 

### ISSUE THREAD

**Issue by alphaleadership** [Sn0wAlice/SensiSafe#1]
serait t'il possible de faire une interface visuel

**Comment by Sn0wAlice** [comment]
Pour ?
c'est un système full api... je ne comprends pas l'intérêt

**Comment by alphaleadership** [comment]
ben une autre branche qui serve de démo d'utilisation

**Comment by Sn0wAlice** [comment]
xD

**Comment by alphaleadership** [comment]
non car je tavoue que je vois pas comment elle s'utilise ou tu a bloquée les navigateur

**Comment by Sn0wAlice** [comment]
added "./examples"

no more help to usage
